apiVersion: v1
entries:
  nuclio:
  - apiVersion: v1
    appVersion: 0.2.2
    created: 2018-01-02T14:54:42.339032+02:00
    description: Serverless for Real-Time and Data-Driven Applications
    digest: 9491729d5d9ab8a8364f17cf9d01f613625b43574507c263b94e3ea73b1eb60a
    home: https://nuclio.io
    icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
    maintainers:
    - email: eliranb@iguazio.com
      name: bivas
    name: nuclio
    sources:
    - https://github.com/nuclio/nuclio
    urls:
    - https://nuclio.github.io/nuclio/charts/nuclio-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.2.1
    created: 2018-01-02T14:54:42.338482+02:00
    description: Serverless for Real-Time and Data-Driven Applications
    digest: 029ad65ebb4f9136fa7f8ce5a86d1836ffdcb8491e58e2a8109a35b9255e0f56
    home: https://nuclio.io
    icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
    maintainers:
    - email: eliranb@iguazio.com
      name: bivas
    name: nuclio
    sources:
    - https://github.com/nuclio/nuclio
    urls:
    - https://nuclio.github.io/nuclio/charts/nuclio-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 0.2.0
    created: 2018-01-02T14:54:42.338118+02:00
    description: A Helm chart for installing nuclio
    digest: 3dc239394c21a214cfec2540bd68669d09e4f108c5a2d387c2db25c3430d2244
    home: https://nuclio.io
    icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
    maintainers:
    - email: eliranb@iguazio.com
      name: Eliran Bivas
    name: nuclio
    sources:
    - https://github.com/nuclio/nuclio
    urls:
    - https://nuclio.github.io/nuclio/charts/nuclio-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: 2018-01-02T14:54:42.337764+02:00
    description: A Helm chart for installing nuclio
    digest: 987c21b1c69c2fdbf918c85272fe18b950091830c8915791fa8b24f53505fd7c
    home: https://nuclio.io
    maintainers:
    - email: eliranb@iguazio.com
      name: Eliran Bivas
    name: nuclio
    sources:
    - https://github.com/nuclio/nuclio
    urls:
    - https://nuclio.github.io/nuclio/charts/nuclio-0.1.0.tgz
    version: 0.1.0
generated: 2018-01-02T14:54:42.336749+02:00
